### ISSUE TITLE
Версия 0.9.1 не стартует вебсервер

### ISSUE THREAD

**Issue by yakovsudarushkin** [EvilBeaver/OneScript.Web#90]
Приветствую.
Первый раз скачивал движок.
Скачал сразу 0.9.1. Веб сервер не запустился. Выдал ошибку.
После этого скачал предыдущую версию 0.9.0 - веб сервер запустился.

Ниже написал текст вызова и ошибки:

PS C:\MyFiles\практика OneScript\Web_1\src> & 'C:\Program Files\OneScriptWeb\OneScript.WebHost.exe'
dbug: OneScript.WebHost.Application.ApplicationInstance[0]
      No database configured
Application startup exception: System.InvalidOperationException: Unknown database type in configuration
   at OneScript.WebHost.Database.DatabaseExtensions.ConfigureDbOptions(IServiceProvider serviceProvider) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Database/DatabaseExtensions.cs:line 65
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)    
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at OneScript.WebHost.BackgroundJobs.BackgroundJobsExtensions.PrepareBgJobsEnvironment(IServiceProvider services, RuntimeEnvironment environment) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/BackgroundJobs/BackgroundJobsExtensions.cs:line 81
   at OneScript.WebHost.Startup.PrepareEnvironment(IServiceProvider services) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Startup.cs:line 149
   at OneScript.WebHost.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IServiceProvider services) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Startup.cs:line 95
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.WebHost[6]
      Application startup exception
System.InvalidOperationException: Unknown database type in configuration
   at OneScript.WebHost.Database.DatabaseExtensions.ConfigureDbOptions(IServiceProvider serviceProvider) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Database/DatabaseExtensions.cs:line 65
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)    
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at OneScript.WebHost.BackgroundJobs.BackgroundJobsExtensions.PrepareBgJobsEnvironment(IServiceProvider services, RuntimeEnvironment environment) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/BackgroundJobs/BackgroundJobsExtensions.cs:line 81
   at OneScript.WebHost.Startup.PrepareEnvironment(IServiceProvider services) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Startup.cs:line 149
   at OneScript.WebHost.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IServiceProvider services) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Startup.cs:line 95
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
Unhandled exception. System.InvalidOperationException: Unknown database type in configuration
   at OneScript.WebHost.Database.DatabaseExtensions.ConfigureDbOptions(IServiceProvider serviceProvider) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Database/DatabaseExtensions.cs:line 65
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)    
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
jenkins_home/workspace/1Script.Web_master/src/OneScript/BackgroundJobs/BackgroundJobsExtensions.cs:line 81
   at OneScript.WebHost.Startup.PrepareEnvironment(IServiceProvider services) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Startup.cs:line 149
   at OneScript.WebHost.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IServiceProvider services) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Startup.cs:line 95
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at OneScript.WebHost.Program.Main(String[] args) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Program.cs:line 84
PS C:\MyFiles\практика OneScript\Web_1\src> & 'C:\Program Files\OneScriptWeb\OneScript.WebHost.exe'
dbug: OneScript.WebHost.Application.ApplicationInstance[0]
      No database configured
Application startup exception: System.InvalidOperationException: Unknown database type in configuration
   at OneScript.WebHost.Database.DatabaseExtensions.ConfigureDbOptions(IServiceProvider serviceProvider) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Database/DatabaseExtensions.cs:line 65
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)    
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at OneScript.WebHost.BackgroundJobs.BackgroundJobsExtensions.PrepareBgJobsEnvironment(IServiceProvider services, RuntimeEnvironment environment) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/BackgroundJobs/BackgroundJobsExtensions.cs:line 81
   at OneScript.WebHost.Startup.PrepareEnvironment(IServiceProvider services) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Startup.cs:line 149
   at OneScript.WebHost.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IServiceProvider services) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Startup.cs:line 95
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.WebHost[6]
      Application startup exception
System.InvalidOperationException: Unknown database type in configuration
   at OneScript.WebHost.Database.DatabaseExtensions.ConfigureDbOptions(IServiceProvider serviceProvider) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Database/DatabaseExtensions.cs:line 65
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)    
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at OneScript.WebHost.BackgroundJobs.BackgroundJobsExtensions.PrepareBgJobsEnvironment(IServiceProvider services, RuntimeEnvironment environment) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/BackgroundJobs/BackgroundJobsExtensions.cs:line 81
   at OneScript.WebHost.Startup.PrepareEnvironment(IServiceProvider services) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Startup.cs:line 149
   at OneScript.WebHost.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IServiceProvider services) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Startup.cs:line 95
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
Unhandled exception. System.InvalidOperationException: Unknown database type in configuration
   at OneScript.WebHost.Database.DatabaseExtensions.ConfigureDbOptions(IServiceProvider serviceProvider) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Database/DatabaseExtensions.cs:line 65
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)    
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
jenkins_home/workspace/1Script.Web_master/src/OneScript/BackgroundJobs/BackgroundJobsExtensions.cs:line 81
   at OneScript.WebHost.Startup.PrepareEnvironment(IServiceProvider services) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Startup.cs:line 149
   at OneScript.WebHost.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IServiceProvider services) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Startup.cs:line 95
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at OneScript.WebHost.Program.Main(String[] args) in /var/jenkins_home/workspace/1Script.Web_master/src/OneScript/Program.cs:line 84

**Comment by yakovsudarushkin** [comment]
после перезапуска VSCode и 0.9.0 не запустил веб сервер

**Comment by nixel2007** [comment]
Добрый день. Что за приложение вы запускаете? Оно содержит обращение к базе данных? Если да, то вы прописали данные подключения к базе в appsettings.json?

**Comment by yakovsudarushkin** [comment]
Запускаю 'C:\Program Files\OneScriptWeb\OneScript.WebHost.exe'
Это распакованный архив с версией 0.9.0

**Comment by nixel2007** [comment]
Я не про движок, я про ваш проект с main.os

**Comment by yakovsudarushkin** [comment]
> Добрый день. Что за приложение вы запускаете? Оно содержит обращение к базе данных? Если да, то вы прописали данные подключения к базе в appsettings.json?

Вот содержимое appsettings.json из папки C:\Program Files\OneScriptWeb

{
  "OneScript": {
    "lib.system": "$appBinary/oscript_modules",
    "lib.additional": [ "oscript_modules" ]
  },
  "Environment": "Development",
  "urls": "http://localhost:5000/"

}

**Comment by yakovsudarushkin** [comment]
> Я не про движок, я про ваш проект с main.os

Проект шаблонный. "Болванка" https://infostart.ru/1c/articles/783435/

**Comment by yakovsudarushkin** [comment]
Пардон. Был невнимателен.
Не оттуда запускал веб сервер. Теперь опять все получилось.

PS C:\MyFiles\практика OneScript\Web_1\src> & 'C:\Program Files\OneScriptWeb\OneScript.WebHost.exe'
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\yakov\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Development
Content root path: C:\MyFiles\практика OneScript\Web_1\src
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.

**Comment by yakovsudarushkin** [comment]
Спасибо за отклик, очень помогли

**Comment by nixel2007** [comment]
Вероятно, речь об этом.

https://github.com/EvilBeaver/webapp-template

@EvilBeaver кажется, ты с @arkuznetsov на днях что-то менял в инициализации подключения к бд. Не могли регресс словить?

**Comment by nixel2007** [comment]
А, ну и хорошо :)

**Comment by yakovsudarushkin** [comment]
> Вероятно, речь об этом.
> 
> https://github.com/EvilBeaver/webapp-template
> 
> @EvilBeaver кажется, ты с @arkuznetsov на днях что-то менял в инициализации подключения к бд. Не могли регресс словить?

Опять распаковал и попробовал запустить движок версии 0.9.1 - не запускается
Вернул версию 0.9.0 - запустился.

**Comment by arkuznetsov** [comment]
> Вероятно, речь об этом.
> 
> https://github.com/EvilBeaver/webapp-template
> 
> @EvilBeaver кажется, ты с @arkuznetsov на днях что-то менял в инициализации подключения к бд. Не могли регресс словить?

Полечено в develop.

**Comment by EvilBeaver** [comment]
Да, ошибка известна, исправим. Пока советую пользоваться 0.9.0 или 0.8

**Comment by nixel2007** [comment]
Альтернативный вариант - взять ночную сборку с build.oscript.io :)
Но могут быть другие проблемы

**Comment by EvilBeaver** [comment]
@yakovsudarushkin @arkuznetsov - коллеги, попробуйте потестировать эту сборку: https://build.oscript.io/job/1Script.Web/job/hotfix%252F0.9.2/1/

**Comment by arkuznetsov** [comment]
> @yakovsudarushkin @arkuznetsov - коллеги, попробуйте потестировать эту сборку: [build.oscript.io/job/1Script.Web/job/hotfix%252F0.9.2/1](https://build.oscript.io/job/1Script.Web/job/hotfix%252F0.9.2/1/)

Я вроде как тестил, работает.

**Comment by yakovsudarushkin** [comment]
> @yakovsudarushkin @arkuznetsov - коллеги, попробуйте потестировать эту сборку: https://build.oscript.io/job/1Script.Web/job/hotfix%252F0.9.2/1/

У меня заработал этот дистрибутив.
Есть небольшая разница, в логах.

### Это версия 0.9.0
PS C:\MyFiles\практика OneScript\Web_1\src> & 'C:\Program Files\OneScriptWeb090\OneScript.WebHost.exe'
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\yakov\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Development
Content root path: C:\MyFiles\практика OneScript\Web_1\src
Now listening on: http://localhost:5000

### Это версия по ссылке, видимо 0.9.2. Тут дополнительно про "No database configured" сообщает 

PS C:\MyFiles\практика OneScript\Web_1\src> & 'C:\Program Files\OneScriptWeb\OneScript.WebHost.exe'
**dbug: OneScript.WebHost.Application.ApplicationInstance[0]
      No database configured**
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\yakov\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Development
Content root path: C:\MyFiles\практика OneScript\Web_1\src
Now listening on: http://localhost:5000

**Comment by EvilBeaver** [comment]
Да, это сообщение уровня Debug. Его можно отключить, подняв уровень логирования в appsettings.json до INFO
